# Trying to get Dev env running in docker
# Nextup: hosted minized thingy, when ever I get everything working as dev

FROM node:16

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# add app
COPY . ./

EXPOSE 8080

CMD [ "nodemon", "start" ]