# AAhhh.. Types are broken for dev as front uses some backend typedeclarations. Fix maybe someday
# or just make a relase dockerfile so there is no need to think about types

# Trying to get Dev env running in docker
# Nextup: hosted minized thingy, when ever I get everything working as dev

FROM node:16

WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]